// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: proto/template.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Chat_MessageStream_FullMethodName        = "/proto.Chat/MessageStream"
	Chat_ConnectToServer_FullMethodName      = "/proto.Chat/ConnectToServer"
	Chat_DisconnectFromServer_FullMethodName = "/proto.Chat/DisconnectFromServer"
)

// ChatClient is the client API for Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatClient interface {
	MessageStream(ctx context.Context, opts ...grpc.CallOption) (Chat_MessageStreamClient, error)
	ConnectToServer(ctx context.Context, opts ...grpc.CallOption) (Chat_ConnectToServerClient, error)
	DisconnectFromServer(ctx context.Context, in *ClientName, opts ...grpc.CallOption) (*Ack, error)
}

type chatClient struct {
	cc grpc.ClientConnInterface
}

func NewChatClient(cc grpc.ClientConnInterface) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) MessageStream(ctx context.Context, opts ...grpc.CallOption) (Chat_MessageStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Chat_ServiceDesc.Streams[0], Chat_MessageStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &chatMessageStreamClient{stream}
	return x, nil
}

type Chat_MessageStreamClient interface {
	Send(*ChatMessage) error
	Recv() (*ChatMessage, error)
	grpc.ClientStream
}

type chatMessageStreamClient struct {
	grpc.ClientStream
}

func (x *chatMessageStreamClient) Send(m *ChatMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatMessageStreamClient) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatClient) ConnectToServer(ctx context.Context, opts ...grpc.CallOption) (Chat_ConnectToServerClient, error) {
	stream, err := c.cc.NewStream(ctx, &Chat_ServiceDesc.Streams[1], Chat_ConnectToServer_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &chatConnectToServerClient{stream}
	return x, nil
}

type Chat_ConnectToServerClient interface {
	Send(*ChatMessage) error
	CloseAndRecv() (*Ack, error)
	grpc.ClientStream
}

type chatConnectToServerClient struct {
	grpc.ClientStream
}

func (x *chatConnectToServerClient) Send(m *ChatMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatConnectToServerClient) CloseAndRecv() (*Ack, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Ack)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatClient) DisconnectFromServer(ctx context.Context, in *ClientName, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, Chat_DisconnectFromServer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServer is the server API for Chat service.
// All implementations must embed UnimplementedChatServer
// for forward compatibility
type ChatServer interface {
	MessageStream(Chat_MessageStreamServer) error
	ConnectToServer(Chat_ConnectToServerServer) error
	DisconnectFromServer(context.Context, *ClientName) (*Ack, error)
	mustEmbedUnimplementedChatServer()
}

// UnimplementedChatServer must be embedded to have forward compatible implementations.
type UnimplementedChatServer struct {
}

func (UnimplementedChatServer) MessageStream(Chat_MessageStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method MessageStream not implemented")
}
func (UnimplementedChatServer) ConnectToServer(Chat_ConnectToServerServer) error {
	return status.Errorf(codes.Unimplemented, "method ConnectToServer not implemented")
}
func (UnimplementedChatServer) DisconnectFromServer(context.Context, *ClientName) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisconnectFromServer not implemented")
}
func (UnimplementedChatServer) mustEmbedUnimplementedChatServer() {}

// UnsafeChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServer will
// result in compilation errors.
type UnsafeChatServer interface {
	mustEmbedUnimplementedChatServer()
}

func RegisterChatServer(s grpc.ServiceRegistrar, srv ChatServer) {
	s.RegisterService(&Chat_ServiceDesc, srv)
}

func _Chat_MessageStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServer).MessageStream(&chatMessageStreamServer{stream})
}

type Chat_MessageStreamServer interface {
	Send(*ChatMessage) error
	Recv() (*ChatMessage, error)
	grpc.ServerStream
}

type chatMessageStreamServer struct {
	grpc.ServerStream
}

func (x *chatMessageStreamServer) Send(m *ChatMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatMessageStreamServer) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Chat_ConnectToServer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServer).ConnectToServer(&chatConnectToServerServer{stream})
}

type Chat_ConnectToServerServer interface {
	SendAndClose(*Ack) error
	Recv() (*ChatMessage, error)
	grpc.ServerStream
}

type chatConnectToServerServer struct {
	grpc.ServerStream
}

func (x *chatConnectToServerServer) SendAndClose(m *Ack) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatConnectToServerServer) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Chat_DisconnectFromServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).DisconnectFromServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_DisconnectFromServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).DisconnectFromServer(ctx, req.(*ClientName))
	}
	return interceptor(ctx, in, info, handler)
}

// Chat_ServiceDesc is the grpc.ServiceDesc for Chat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DisconnectFromServer",
			Handler:    _Chat_DisconnectFromServer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MessageStream",
			Handler:       _Chat_MessageStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ConnectToServer",
			Handler:       _Chat_ConnectToServer_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/template.proto",
}
